src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * User
 *
 * @ORM\Table(name="user", uniqueConstraints={@ORM\UniqueConstraint(name="UNIQ_8D93D649E7927C74", columns={"email"})})
 * @ORM\Entity
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 */
class User implements UserInterface,\Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=180, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Email(message = "The email '{{ value }}' is not a valid email.")
     */
    private $email;

    /**
     * @var array
     *
     * @ORM\Column(name="roles", type="json", nullable=false)
     */
    private $roles = [];

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255, nullable=false)
     * @Assert\Length(min=6)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="last_name", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="personal_code", type="string", nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(min=10)
     */
    private $personalCode;

    /**
     * @var string
     *
     * @ORM\Column(name="phone", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(min=9)
     */
    private $phone;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(name="city", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     */
    private $city;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="users", fileNameProperty="document")
     * 
     * @var File|null
     */
    private $imageFile;

    /**
     * @var string|null
     * 
     * @ORM\Column(name="document", type="string", length=255)
     */
    private $document;

    /**
     * @var \DateTimeInterface|null
     * 
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\OneToMany(targetEntity="Votes", mappedBy="user")
     */
    private $votes;

    public function __construct()
    {
        $this->votes = new ArrayCollection();
        $this->updated_at = new \DateTime('now');
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updated_at = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): ?array
    {
        $roles = $this->roles;
        // give everyone ROLE_USER!
        if (!in_array('ROLE_USER', $roles)) {
            $roles[] = 'ROLE_USER';
        }

        return $roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPersonalCode(): ?string
    {
        return $this->personalCode;
    }

    public function setPersonalCode(string $personalCode): self
    {
        $this->personalCode = $personalCode;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->getEmail();
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
    }

    public function serialize()
    {
        return serialize([
            $this->id,
            $this->email,
            $this->password
        ]);
    }

    public function unserialize($serialized)
    {
        list(
            $this->id,
            $this->email,
            $this->password
        ) = unserialize($serialized, ["allowed_classes" => false]);
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
    * Get $document
    * @return string
    */
    public function getDocument(): ?string
    {
        return $this->document;
    }

    /**
    * Set $document
    * @param string $document
    */
    public function setDocument(?string $document): self
    {
        $this->document = $document;

        return  $this;
    }

    /**
     * @return Collection|Votes[]
     */
    public function getVotes(): Collection
    {
        return $this->votes;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('email', EmailType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a password',
                    ]),
                    new Email([
                        'message' => 'Invalid email address',
                    ])
                ]
            ])
            ->add('roles', ChoiceType::class, [
                'choices' => [
                    'Utilisateur' => 'ROLE_USER',
                    'Administrateur' => 'ROLE_ADMIN'
                ],
                'expanded' => true,
                'multiple' => true,
                'label' => 'Rôles'
            ])
            ->add('firstName', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a firstName',
                    ]),
                    new Length(['min' => 3]),
                    new Regex([
                        'pattern' => '/\d/',
                        'match' => false,
                        'message' => 'Your firstname cannot contain a number',
                    ])
                ]
            ])
            ->add('lastName', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a lastName',
                    ]),
                    new Length(['min' => 3]),
                    new Regex([
                        'pattern' => '/\d/',
                        'match' => false,
                        'message' => 'Your lastname cannot contain a number',
                    ])
                ]
            ])
            ->add('personalCode', NumberType::class, [
                'constraints' => [
                    new Regex([
                        'pattern' => '/^(0|[1-9][0-9]*)$/',
                        'match' => true,
                        'message' => 'Your personal code cannot contain a letter',
                    ])
                ]
            ])
            ->add('phone', TextType::class, [
                'constraints' => [
                    new Regex([
                        'pattern' => '/^[0-9\-\+]{9,15}$/',
                        'match' => true,
                        'message' => 'Your phone number does not have the expected format',
                    ])
                ]
            ])
            ->add('address', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter an address',
                    ])
                ]
            ])
            ->add('city', TextType::class, [
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter a city',
                    ])
                ]
            ])
            ->add('imageFile', VichImageType::class, [
                'required' => false,
                'constraints' => [
                    new File([
                        'mimeTypes' => [
                            'image/png',
                            'image/jpx',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image file',
                    ])
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/User/UserHomeController.php
<?php

namespace App\Controller\User;

use App\Entity\Company;
use App\Entity\NominationYear;
use App\Entity\Votes;
use App\Repository\NominationYearRepository;
use App\Repository\UserRepository;
use App\Repository\VotesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity as TakeId;


/**
 * Class UserHomeController
 * @package App\Controller\User
 * @Route("/user",name="user_")
 */
class UserHomeController extends AbstractController
{
    private $user;


    public function __construct(UserRepository $user)
    {
        $this->user = $user;
    }

    /**
     * @Route("/",name="home")
     * @param Request $request
     * @param NominationYearRepository $nominationYearRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function index(Request $request, NominationYearRepository $nominationYearRepository): Response
    {
        $user = $this->user->findOneBy(['email' => $request->getSession()->get("email")]);

        $nominationsYears = $nominationYearRepository->findAll();
        //dump($user);
        return $this->render("user/userIndex.html.twig",compact("user","nominationsYears"));

    }

    /**
     * @Route("/nominationYear/votes",name="ny_vote")
     * @param NominationYearRepository $nominationYearRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function getNominationYearVote(NominationYearRepository $nominationYearRepository)
    {
        return $this->render("user/userNominationYearVotes.html.twig",[
            'NominationYear' => $nominationYearRepository->findAll(),
            'curentValue' => 'VotesUser'
        ]);
    }


    /**
     * @Route("/nominationYear/{idNy}/company",name="company")
     * @TakeId("nominationYear", expr="repository.find(idNy)")
     * @param NominationYear $nominationYear
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function ChoiceCompagnyForVote( NominationYear $nominationYear): \Symfony\Component\HttpFoundation\Response
    {


        return $this->render("user/userCompany.html.twig",
            [
                'companys' => $nominationYear->getCompany(),'idNy' => $nominationYear,
                'curentValue' => 'VotesUser'

            ]);
    }

    /**
     * @Route("/nominationYear/{idNy}/compagny/{idComp}/",name="vote")
     * @TakeId("company", expr="repository.find(idComp)")
     * @TakeId("nominationYear", expr="repository.find(idNy)")
     * @param Company $company
     * @param NominationYear $nominationYear
     * @param EntityManagerInterface $manager
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function VoteForCompagnyInCategorie(Request $request, Company $company, NominationYear $nominationYear, EntityManagerInterface $manager)
    {

        $user = $this->user->findOneBy(['email' => $request->getSession()->get("email")]);
        $vote = new Votes();
        $vote->setDate(new \DateTime('now'));
        $vote->setNominationYear($nominationYear);
        $vote->setCompany($company);
        $vote->setUser($user);
        $manager->persist($vote);
        $manager->flush();
        $this->addFlash("vote", "Votre vote a été pris en compte merci.");
        return $this->redirectToRoute('user_ny_vote');
    }

    /**
     * @Route("/vues_des_votes/", name="view_vote")
     * @param VotesRepository $votesRepository
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function viewVotesUser(Request $request, VotesRepository $votesRepository): Response
    {

        $user = $this->user->findOneBy(['email' => $request->getSession()->get("email")])->getId();
        $votesUser = $votesRepository->findBy(['user' => $user]);
        //dd($votesUser);
        return $this->render("user/userViewVotes.html.twig",
            [
           'votesUser' => $votesUser,
           'curentValue' => 'VotesViews'
            ]);

    }
    /**
     * @Route("/nominationYear/view",name="ny_view")
     * @param NominationYearRepository $nominationYearRepository
     * @return Response
     */
    public function getNominationYearViews(NominationYearRepository $nominationYearRepository)
    {
        return $this->render("user/userNominationYearViews.html.twig",[
            'NominationYear' => $nominationYearRepository->findAll(),
            'curentValue' => 'NominationYearViews'
        ]);
    }



}

templates/user/userCompany.html.twig
{% extends "base.html.twig" %}

{% block title %}{% trans %}User vote category{% endtrans %}{% endblock %}


{% block body %}
    {{ include('user/userHeaderTemplate.html.twig') }}
            <div class="container jumbotron">
                <div class="row mt-5 d-flex justify-content-center">
                    {% for company in companys%}
                        <div class="card mx-3" style="width: 18rem;">
                            <img src="{{ vich_uploader_asset(company, 'imageFile') }}" class="card-img-top" alt="foret">
                            <div class="card-body">
                                <h5 class="card-title">{{ company.name }}</h5>
                                <p class="card-text">Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                                <a href="{{ path('user_vote',{'idNy': idNy.id, 'idComp': company.id}) }}" class="btn btn-primary ">{% trans %}Vote for{% endtrans %}: {{ company.name}}</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
{% endblock %}

templates/user/userHeaderTemplate.html.twig
<hr>
		<div class="container">
			<div class="row my-5">
				<h1 class="display-4 text-white font-weight-bold">{% trans %}Welcome to your account interface{% endtrans %}
					{% if app.user %}
						{{ app.user.username }}
					{% endif %}
				</h1>
			</div>
		</div>
<hr>

templates/user/userIndex.html.twig
{% extends "base.html.twig" %}

{% block title %}{% trans %}User vote category{% endtrans %}{% endblock %}


{% block body %}
    {{ include('user/userHeaderTemplate.html.twig') }}
    {{ include('home.html.twig') }}
{% endblock %}

templates/user/userNominationYearTemplate.html.twig
<div class="card mx-3 mt-3" style="width: 18rem;">
    <img src="{{ vich_uploader_asset(ny.category, 'imageFile') }}" class="card-img-top" alt="foret">
    <div class="card-body">
        <h5 class="card-title">{{ ny.category.category }}</h5>
        <h3 class="card-title">{{ ny.dateNominationYear|date("m/d/Y") }}</h3>
        {% if curentValue is defined and curentValue == 'VotesUser' %}
        <a class="btn btn-primary" href="{{ path("user_company", {'idNy': ny.id}) }}">{% trans %}Vote for{% endtrans %}: {{ ny.category.category }} </a>
        {% endif %}
    </div>

</div>

templates/user/userNominationYearViews.html.twig
{% extends "base.html.twig" %}

{% block title %}{% trans %}User vote category{% endtrans %}{% endblock %}


{% block body %}
    {{ include('user/userHeaderTemplate.html.twig') }}
            <div class="container ">
                <div class="row">
                    <h1 class="text-white">{% trans %}Nominated{% endtrans %}: </h1>
                </div>
                <div class="row mt-5 d-flex justify-content-center">
                    {% for ny in NominationYear %}
                        {{ include('user/userNominationYearTemplate.html.twig') }}
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/user/userNominationYearVotes.html.twig
{% extends "base.html.twig" %}

{% block title %}{% trans %}User vote category{% endtrans %}{% endblock %}


{% block body %}
    {{ include('user/userHeaderTemplate.html.twig') }}

    <div class="container ">
        <div class="row">
            {% for message in app.flashes('vote') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <h1 class="text-white">{% trans %}Vote for a nominated company{% endtrans %}: </h1>
        </div>
        <div class="row mt-5 d-flex justify-content-center">
            {% for ny in NominationYear %}
                {% if not is_granted('NominationYear', ny) %}
                    {{ include('user/userNominationYearTemplate.html.twig') }}
                {% endif %}
            {% endfor %}
        </div>
</div>
{% endblock %}

templates/user/userViewVotes.html.twig
{% extends "base.html.twig" %}

{% block title %}{% trans %}Homepage{% endtrans %}{% endblock %}

{% block body %}
    {{ include('user/userHeaderTemplate.html.twig') }}
    <div class="container ">
        <div class="row">
        <h1 class="text-white">{% trans %}Your votes{% endtrans %}: </h1>
        </div>
        <table class="table ttable-hover table-striped text-center mt-4 text-white">
            <thead>
            <th scope="col">{% trans %}Date of the vote{% endtrans %}</th>
            <th scope="col">{% trans %}Category{% endtrans %}</th>
            <th scope="col">{% trans %}Company{% endtrans %}</th>
            <th scope="col">{% trans %}Nomination date{% endtrans %}</th>
            </thead>
            <tbody>
            {% for vU in votesUser %}
                <tr>
                    <td>
                        {{ vU.date|date("m/d/Y")}}
                    </td>
                    <td>
                        {{ vU.nominationYear.category.category }}</br>
                        <img src="{{ vich_uploader_asset(vU.nominationYear.category, 'imageFile') }}" width="56em" height="56em" alt="{{ vU.nominationYear.category.document }}" /></td>
                    </td>
                    <td>
                        {{ vU.company.name }}</br>
                        <img src="{{ vich_uploader_asset(vU.company, 'imageFile') }}" width="56em" height="56em" alt="{{ vU.company.document }}" />
                    </td>
                    <td>
                        {{ vU.nominationYear.dateNominationYear|date("m/d/Y")}}
                    </td>
                </tr>
            {% else %}
                <p>{% trans %}No registered category{% endtrans %}</p>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}